server:
  port: 3000

pig:
  auth:
    clientId: pig
    clientSecret: pig
    scope: server

spring:
  redis:
    host: 122.112.219.254
    port: 6379
    password: 1234xxxxx
    
logging:
  config: classpath:logback.xml

